apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: workshop
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000  # Assuming your application is running on port 3000 in the pods
  type: NodePort
  selector:
    role: frontend

